---
# clickhouse_01_ext_ip: "127.0.0.1"
vector_config_dir: "/etc/vector"
#ansible_user: ansible

vector_config:

    sources:
      dummy_logs:
        type: demo_logs
        format: syslog
        interval: 1
    transforms:
      parse_logs:
        type: remap
        inputs:
          - dummy_logs
        source: |
          . = parse_syslog!(string!(.message))
    sinks:
      print:
        type: console
        inputs:
          - parse_logs
        encoding:
          codec: json
