server.name: kibana
server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: ["http://es-hot:9200","http://es-warm:/9200"]
monitoring.ui.container.elasticsearch.enabled: true
xpack.security.enabled: 'false'