resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    all:
      hosts:
        sonar-01:
          ansible_host: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
        nexus-01:
          ansible_host: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
      children:
        sonarqube:
          hosts:
            sonar-01:
        nexus:
          hosts:
            nexus-01:
        postgres:
          hosts:
            sonar-01:
      vars:
        ansible_connection_type: paramiko
        #ansible_user: centos
  DOC
  filename = "../infrastructure/inventory/cicd/hosts.yml"
}  
# resource "local_file" "all_vars" {
#   content = <<-DOC
#   # Ansible vars containing variable values from Terraform.
#   # Generated by Terraform.

#     clickhouse_01_ext_ip: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
#     vector_01_ext_ip: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
#   DOC
#   filename = "../infrastructure/group_vars/all.yml"

# #  depends_on = [
# #    yandex_compute_instance.node01,
# #    yandex_compute_instance.node02
# #  ]
# }