{
 "title": "dashboard1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество места на файловой системе",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_load1{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(instance) (rate(node_load5{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(instance) (rate(node_load15{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_cpu_seconds_total{instance=\"node-exporter:9100\", mode=\"idle\"}[$__rate_interval]))*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}