---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: quay.io/centos/centos:stream8 #docker.io/pycontribs/centos:8
    dockerfile: ../resources/Dockerfile.j2
    #pre_build_image: true
    privileged: true
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker
      
    #command: "/sbin/init"
  # - name: centos7
  #   image: quay.io/centos/centos:7
  #   pre_build_image: true
  #   #privileged: true
  #   #command: /sbin/init
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
  inventory:
    links:
      hosts: ../resources/inventory/hosts.yml
      group_vars: ../resources/inventory/group_vars/
      host_vars: ../resources/inventory/host_vars/
verifier:
  name: ansible
