resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    ---
    all:
      hosts:
        jenkins-master-01:
          ansible_host: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
        jenkins-agent-01:
          ansible_host: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
      children:
        jenkins:
          children:
            jenkins_masters:
              hosts:
                jenkins-master-01:
            jenkins_agents:
              hosts:
                jenkins-agent-01:
      vars:
        ansible_connection_type: paramiko
        ansible_user: centos
  DOC
  filename = "../inventory/cicd/prod.yml"
}  
resource "local_file" "all_vars" {
  content = <<-DOC
  # Ansible vars containing variable values from Terraform.
  # Generated by Terraform.

    jenkins-master-01_ext_ip: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    jenkins-agent-01_ext_ip: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
  DOC
  filename = "../inventory/cicd/group_vars/all.yml"

#  depends_on = [
#    yandex_compute_instance.node01,
#    yandex_compute_instance.node02
#  ]
}