resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    vector:
      hosts:
        vector-01:
          ansible_host: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: ${yandex_compute_instance.node03.network_interface.0.nat_ip_address}
  DOC
  filename = "../ansible/inventory/prod.yml"
}  
resource "local_file" "all_vars" {
  content = <<-DOC
  # Ansible vars containing variable values from Terraform.
  # Generated by Terraform.

    clickhouse_01_ext_ip: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    vector_01_ext_ip: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
    lighthouse_01_ext_ip: ${yandex_compute_instance.node03.network_interface.0.nat_ip_address}
  DOC
  filename = "../ansible/group_vars/all.yml"

#  depends_on = [
#    yandex_compute_instance.node01,
#    yandex_compute_instance.node02
#  ]
}