version: '3.0'
services:

  es-hot:
    image: elasticsearch:7.17.2
    container_name: es-hot
    environment:
      - node.name=es-hot
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-warm
      - cluster.initial_master_nodes=es-hot,es-warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - hot_data:/usr/share/elasticsearch/data:Z
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - elk-net
    depends_on:
      - es-warm

  es-warm:
    image: elasticsearch:7.17.2
    container_name: es-warm
    environment:
      - node.name=es-warm
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-hot
      - cluster.initial_master_nodes=es-hot,es-warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - warm_data:/usr/share/elasticsearch/data:Z
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk-net

  kibana:
    image: kibana:7.17.2
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
       - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk-net
    depends_on:
      - es-hot
      - es-warm

  logstash:
    image: logstash:7.17.2
    container_name: logstash
    volumes:
      - ./configs/pipeline:/usr/share/logstash/pipeline:ro
      # - ./configs/logstash.conf:/etc/logstash/conf.d/logstash.conf:Z
      # - ./configs/logstash.yml:/opt/logstash/config/logstash.yml:Z
    ports:
      - 5044:5044
      - 5046:5046
    networks:
      - elk-net
    depends_on:
      - es-hot
      - es-warm

  filebeat:
    image: elastic/filebeat:7.17.2
    container_name: filebeat
    privileged: true
    user: root
    volumes:
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:Z
      - /var/lib/docker:/var/lib/docker:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    command:
      - "-e"
      - "--strict.perms=false"    
    depends_on:
      - logstash

  some_application:
    image: library/python:3.9-alpine
    container_name: some_app
    volumes:
      - ./pinger/run.py:/opt/run.py:Z
    entrypoint: python3 /opt/run.py

volumes:
  hot_data:
    driver: local
  warm_data:
    driver: local

networks:
  elk-net:
    driver: bridge
